version: '3.8'
services:
  mock-hue:
    build:
      context: ./mock_bridge
    container_name: mock-hue
    ports:
      - "5000:5000"
  mcp-server:
    build:
      context: ./mcp_server
    container_name: mcp-server
    environment:
      HUE_BRIDGE_IP: mock-hue:5000
      HUE_USERNAME: testuser
      GOOGLE_CLIENT_ID: ${HUE_MCP_GOOGLE_CLIENT_ID}
      ALLOWED_EMAILS: ${HUE_MCP_ALLOWED_EMAILS}
      TAILSCALE_FUNNEL_URL: ${HUE_MCP_TAILSCALE_FUNNEL_URL}
    ports:
      - "8000:8000"
    depends_on:
      - mock-hue
