services:
  mock-hue:
    build:
      context: ./mock_bridge
    container_name: mock-hue
    ports:
      - "5000:5000"
    volumes:
      - ./mock_bridge/src:/app/src
    working_dir: /app/src
    command: python mock_hue.py
  mcp-server:
    build:
      context: ./mcp_server
    container_name: mcp-server
    environment:
      HUE_BRIDGE_IP: mock-hue:5000
      HUE_USERNAME: testuser
      GOOGLE_CLIENT_ID: ${HUE_MCP_GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${HUE_MCP_GOOGLE_CLIENT_SECRET}
      ALLOWED_EMAILS: ryderdamen@gmail.com
      TAILSCALE_FUNNEL_URL: ${HUE_MCP_TAILSCALE_FUNNEL_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./mcp_server/src:/app/src
    working_dir: /app/src
    depends_on:
      - mock-hue
